In [7]:
import pandas as pd

In [9]:
df = pd.read_csv("../day-03/data/sales_data.csv")

In [12]:
df.head()

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie

In [13]:
# select the coulmns 

df['Sales_Amount']

0      5053.97
1      4384.02
2      4631.23
3      2167.94
4      3750.20
        ...
995    4733.88
996    4716.36
997    7629.70
998    1629.47
999    4923.93
Name: Sales_Amount, Length: 1000, dtype: float64

In [14]:
# multipal columns 

df[['Product_Category','Sales_Amount']]

    Product_Category  Sales_Amount
0          Furniture       5053.97
1          Furniture       4384.02
2               Food       4631.23
3           Clothing       2167.94
4        Electronics       3750.20
..               ...           ...
995             Food       4733.88
996         Clothing       4716.36
997         Clothing       7629.70
998      Electronics       1629.47
999             Food       4923.93

[1000 rows x 2 columns]

In [17]:
# Filter the Rows 
# one condition

df[df['Sales_Amount']>5000]

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
7,1087,2023-01-06,Eve,South,7698.92,46,Furniture,3702.51,3964.65,New,0.12,Bank Transfer,Online,South-Eve
9,1075,2023-10-09,Charlie,West,8239.58,18,Clothing,2228.35,2682.34,New,0.13,Bank Transfer,Online,West-Charlie
10,1088,2023-11-16,Eve,North,8518.45,13,Furniture,2440.11,2517.60,New,0.23,Bank Transfer,Retail,North-Eve
12,1024,2023-11-11,Eve,West,6607.80,21,Food,622.01,641.09,Returning,0.00,Bank Transfer,Retail,West-Eve
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
982,1074,2023-12-16,Bob,North,6310.56,19,Furniture,278.67,423.13,New,0.24,Credit Card,Online,North-Bob
983,1039,2023-08-01,Eve,West,7527.63,36,Clothing,2919.00,3125.01,New,0.24,Cash,Online,West-Eve
989,1025,2023-12-30,David,West,9215.32,28,Electronics,2097.84,2270.99,New,0.13,Credit Card,Retail,West-David
994,1068,2023-04-06,Alice,South,9093.50,31,Clothing,3169.37,3304.15,Returning,0.25,Credit Card,Retail,South-Alice
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David

In [18]:
# multipal conditions

df[ (df['Sales_Amount'] > 5000) & (df['Quantity_Sold'] > 10) ]

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
7,1087,2023-01-06,Eve,South,7698.92,46,Furniture,3702.51,3964.65,New,0.12,Bank Transfer,Online,South-Eve
9,1075,2023-10-09,Charlie,West,8239.58,18,Clothing,2228.35,2682.34,New,0.13,Bank Transfer,Online,West-Charlie
10,1088,2023-11-16,Eve,North,8518.45,13,Furniture,2440.11,2517.60,New,0.23,Bank Transfer,Retail,North-Eve
12,1024,2023-11-11,Eve,West,6607.80,21,Food,622.01,641.09,Returning,0.00,Bank Transfer,Retail,West-Eve
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
982,1074,2023-12-16,Bob,North,6310.56,19,Furniture,278.67,423.13,New,0.24,Credit Card,Online,North-Bob
983,1039,2023-08-01,Eve,West,7527.63,36,Clothing,2919.00,3125.01,New,0.24,Cash,Online,West-Eve
989,1025,2023-12-30,David,West,9215.32,28,Electronics,2097.84,2270.99,New,0.13,Credit Card,Retail,West-David
994,1068,2023-04-06,Alice,South,9093.50,31,Clothing,3169.37,3304.15,Returning,0.25,Credit Card,Retail,South-Alice
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David

In [20]:
# sorting 
df['Sales_Amount'].sort_values(ascending=True)

255     100.12
979     106.47
67      113.40
264     114.59
570     119.72
        ...
748    9961.96
654    9972.11
855    9972.66
760    9976.52
755    9989.04
Name: Sales_Amount, Length: 1000, dtype: float64

In [21]:
df['Sales_Amount'].sort_values(ascending=False)

755    9989.04
760    9976.52
855    9972.66
654    9972.11
748    9961.96
        ...
570     119.72
264     114.59
67      113.40
979     106.47
255     100.12
Name: Sales_Amount, Length: 1000, dtype: float64

In [ ]:
# Task

# Answer at least these:

# Products with sales > ₹5,000
# Transactions with quantity > 10
# Top 10 highest-sales transactions
# Customers spending > ₹10,000
# Products sorted highest to lowest revenue

In [ ]:

# Products with sales > ₹5,000

# df[df['Sales_Amount']>5000]['Product_Category']    # single column 
df[ df['Sales_Amount']>5000 ][['Product_Category' , 'Sales_Amount']]   # multipal columns

    Product_Category  Sales_Amount
0          Furniture       5053.97
7          Furniture       7698.92
9           Clothing       8239.58
10         Furniture       8518.45
12              Food       6607.80
..               ...           ...
982        Furniture       6310.56
983         Clothing       7527.63
989      Electronics       9215.32
994         Clothing       9093.50
997         Clothing       7629.70

[501 rows x 2 columns]

In [29]:
# df.loc[ df['Sales_Amount'] > 5000  , 'Product_Category']  # single column 
df.loc[ df['Sales_Amount'] > 5000  , ['Product_Category' , 'Sales_Amount']  ] # multipal columns

    Product_Category  Sales_Amount
0          Furniture       5053.97
7          Furniture       7698.92
9           Clothing       8239.58
10         Furniture       8518.45
12              Food       6607.80
..               ...           ...
982        Furniture       6310.56
983         Clothing       7527.63
989      Electronics       9215.32
994         Clothing       9093.50
997         Clothing       7629.70

[501 rows x 2 columns]

In [35]:
# Transactions with quantity > 10

df[ df['Quantity_Sold'] > 45 ][['Payment_Method','Quantity_Sold']]

    Payment_Method  Quantity_Sold
7    Bank Transfer             46
15            Cash             48
28   Bank Transfer             47
69            Cash             49
73            Cash             49
..             ...            ...
948           Cash             47
957           Cash             49
962  Bank Transfer             48
993    Credit Card             47
999           Cash             48

[89 rows x 2 columns]

In [36]:
df.loc[ df['Quantity_Sold'] > 45 , ['Payment_Method','Quantity_Sold']]

    Payment_Method  Quantity_Sold
7    Bank Transfer             46
15            Cash             48
28   Bank Transfer             47
69            Cash             49
73            Cash             49
..             ...            ...
948           Cash             47
957           Cash             49
962  Bank Transfer             48
993    Credit Card             47
999           Cash             48

[89 rows x 2 columns]

In [43]:
# Top 10 highest-sales transactions

df['Sales_Amount'].sort_values(ascending=False).head(10)

755    9989.04
760    9976.52
855    9972.66
654    9972.11
748    9961.96
796    9956.75
142    9948.71
189    9933.22
89     9914.15
784    9907.72
Name: Sales_Amount, dtype: float64

In [45]:
df.head()

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie

In [48]:
# Customers spending > ₹10,000

df[df['Sales_Amount']>7000][['Customer_Type']]

    Customer_Type
7             New
9             New
10            New
14            New
21            New
..            ...
981           New
983           New
989           New
994     Returning
997     Returning

[302 rows x 1 columns]

In [51]:
df

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning,0.29,Cash,Online,North-Charlie
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New,0.21,Bank Transfer,Retail,North-Bob
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David
998,1100,2023-12-20,David,West,1629.47,39,Electronics,3685.03,3743.39,New,0.01,Bank Transfer,Online,West-David
999,1086,2023-08-16,Alice,East,4923.93,48,Food,2632.58,2926.68,Returning,0.14,Cash,Online,East-Alice

In [54]:
# Products sorted highest to lowest revenue

df.sort_values('Sales_Amount' , ascending=False)[['Sales_Amount','Product_Category']]

     Sales_Amount Product_Category
755       9989.04             Food
760       9976.52        Furniture
855       9972.66         Clothing
654       9972.11         Clothing
748       9961.96        Furniture
..            ...              ...
570        119.72         Clothing
264        114.59             Food
67         113.40        Furniture
979        106.47         Clothing
255        100.12         Clothing

[1000 rows x 2 columns]