In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("employee_data_dirty.csv")

In [4]:
df

,Employee_ID,Name,Age,Department,Salary,Join_Date,City,Email,Temp_Column
0,EMP001,Rahul,25,Data Analytics,45000,2023-01-15,Bengaluru,rahul@gmail.com,123
1,EMP002,Priya,28,HR,52000,2022-06-20,Hyderabad,priya@gmail.com,456
2,EMP003,Amit,24,Data Science,NaN,2023-03-10,Pune,amit@gmail.com,789
3,EMP004,Neha,30,Finance,65000,2021-11-05,Mumbai,neha@gmail.com,111
4,EMP005,Ravi,NaN,IT,48000,2023-07-12,Chennai,ravi@gmail.com,222
5,EMP006,Sneha,27,Data Analytics,55000,NaN,Bengaluru,sneha@gmail.com,333
6,EMP007,Arjun,29,Data Science,60000,2022-09-18,Delhi,arjun@gmail.com,444
7,EMP008,Meera,26,HR,50000,2023-02-28,Hyderabad,meera@gmail.com,555
8,EMP009,Kiran,31,Finance,72000,2020-08-14,Mumbai,NaN,666
9,EMP010,Anjali,25,IT,47000,2023-05-22,Pune,anjali@gmail.com,777
10,EMP010,Anjali,25,IT,47000,2023-05-22,Pune,anjali@gmail.com,777
11,EMP011,Varun,twenty nine,Data Analytics,58000,2022-12-01,Bengaluru,varun@gmail.com,888
12,EMP012,Pooja,27,Data Science,62000,2021-10-10,Chennai,pooja@gmail.com,999
13,EMP013,Rohit,32,Finance,not available,2019-04-15,Mumbai,rohit@gmail.com,101
14,EMP014,Divya,26,HR,51000,2023-06-30,Hyderabad,divya@gmail.com,102
15,EMP015,Manoj,23,IT,42000,2024-01-10,Pune,manoj@gmail.com,103
16,EMP016,Sanjay,28,Data Analytics,57000,2022-02-29,Bengaluru,sanjay@gmail.com,104
17,EMP017,Kavya,27,Data Science,61000,2023-04-05,NaN,kavya@gmail.com,105
18,EMP018,Deepak,35,Finance,75000,2020-12-18,Mumbai,deepak@gmail.com,106
19,EMP019,Swati,24,HR,49000,2023-08-25,Hyderabad,swati@gmail.com,107
20,EMP020,Nikhil,29,IT,53000,2022-07-15,Chennai,nikhil@gmail.com,108

## Detecting & Handling Missing values

In [5]:
df.isnull().sum()

Employee_ID    0
Name           0
Age            1
Department     0
Salary         1
Join_Date      1
City           1
Email          1
Temp_Column    0
dtype: int64

In [6]:
df1 = df.dropna()  # this will remove the nan values 
df1

,Employee_ID,Name,Age,Department,Salary,Join_Date,City,Email,Temp_Column
0,EMP001,Rahul,25,Data Analytics,45000,2023-01-15,Bengaluru,rahul@gmail.com,123
1,EMP002,Priya,28,HR,52000,2022-06-20,Hyderabad,priya@gmail.com,456
3,EMP004,Neha,30,Finance,65000,2021-11-05,Mumbai,neha@gmail.com,111
6,EMP007,Arjun,29,Data Science,60000,2022-09-18,Delhi,arjun@gmail.com,444
7,EMP008,Meera,26,HR,50000,2023-02-28,Hyderabad,meera@gmail.com,555
9,EMP010,Anjali,25,IT,47000,2023-05-22,Pune,anjali@gmail.com,777
10,EMP010,Anjali,25,IT,47000,2023-05-22,Pune,anjali@gmail.com,777
11,EMP011,Varun,twenty nine,Data Analytics,58000,2022-12-01,Bengaluru,varun@gmail.com,888
12,EMP012,Pooja,27,Data Science,62000,2021-10-10,Chennai,pooja@gmail.com,999
13,EMP013,Rohit,32,Finance,not available,2019-04-15,Mumbai,rohit@gmail.com,101
14,EMP014,Divya,26,HR,51000,2023-06-30,Hyderabad,divya@gmail.com,102
15,EMP015,Manoj,23,IT,42000,2024-01-10,Pune,manoj@gmail.com,103
16,EMP016,Sanjay,28,Data Analytics,57000,2022-02-29,Bengaluru,sanjay@gmail.com,104
18,EMP018,Deepak,35,Finance,75000,2020-12-18,Mumbai,deepak@gmail.com,106
19,EMP019,Swati,24,HR,49000,2023-08-25,Hyderabad,swati@gmail.com,107
20,EMP020,Nikhil,29,IT,53000,2022-07-15,Chennai,nikhil@gmail.com,108

In [7]:
df1.isnull().sum()

Employee_ID    0
Name           0
Age            0
Department     0
Salary         0
Join_Date      0
City           0
Email          0
Temp_Column    0
dtype: int64

In [8]:
# handle missing values for salary with mean value only for salary column

# df['Salary'].fillna(df['Salary'].mean())  # error because salary is in categoery type data 

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  21 non-null     object
 1   Name         21 non-null     object
 2   Age          20 non-null     object
 3   Department   21 non-null     object
 4   Salary       20 non-null     object
 5   Join_Date    20 non-null     object
 6   City         20 non-null     object
 7   Email        20 non-null     object
 8   Temp_Column  21 non-null     int64
dtypes: int64(1), object(8)
memory usage: 1.6+ KB

In [9]:
df['Age']

0              25
1              28
2              24
3              30
4             NaN
5              27
6              29
7              26
8              31
9              25
10             25
11    twenty nine
12             27
13             32
14             26
15             23
16             28
17             27
18             35
19             24
20             29
Name: Age, dtype: object

In [10]:
df['Age'][11]

'twenty nine'

In [11]:
df['Age'][11] = '29'
df['Age']

D:\TEMP\ipykernel_11572\2005923554.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'][11] = '29'

0      25
1      28
2      24
3      30
4     NaN
5      27
6      29
7      26
8      31
9      25
10     25
11     29
12     27
13     32
14     26
15     23
16     28
17     27
18     35
19     24
20     29
Name: Age, dtype: object

In [12]:
# remove the entire row
df.dropna(subset='Age' , inplace=True)

In [13]:
df

,Employee_ID,Name,Age,Department,Salary,Join_Date,City,Email,Temp_Column
0,EMP001,Rahul,25,Data Analytics,45000,2023-01-15,Bengaluru,rahul@gmail.com,123
1,EMP002,Priya,28,HR,52000,2022-06-20,Hyderabad,priya@gmail.com,456
2,EMP003,Amit,24,Data Science,NaN,2023-03-10,Pune,amit@gmail.com,789
3,EMP004,Neha,30,Finance,65000,2021-11-05,Mumbai,neha@gmail.com,111
5,EMP006,Sneha,27,Data Analytics,55000,NaN,Bengaluru,sneha@gmail.com,333
6,EMP007,Arjun,29,Data Science,60000,2022-09-18,Delhi,arjun@gmail.com,444
7,EMP008,Meera,26,HR,50000,2023-02-28,Hyderabad,meera@gmail.com,555
8,EMP009,Kiran,31,Finance,72000,2020-08-14,Mumbai,NaN,666
9,EMP010,Anjali,25,IT,47000,2023-05-22,Pune,anjali@gmail.com,777
10,EMP010,Anjali,25,IT,47000,2023-05-22,Pune,anjali@gmail.com,777
11,EMP011,Varun,29,Data Analytics,58000,2022-12-01,Bengaluru,varun@gmail.com,888
12,EMP012,Pooja,27,Data Science,62000,2021-10-10,Chennai,pooja@gmail.com,999
13,EMP013,Rohit,32,Finance,not available,2019-04-15,Mumbai,rohit@gmail.com,101
14,EMP014,Divya,26,HR,51000,2023-06-30,Hyderabad,divya@gmail.com,102
15,EMP015,Manoj,23,IT,42000,2024-01-10,Pune,manoj@gmail.com,103
16,EMP016,Sanjay,28,Data Analytics,57000,2022-02-29,Bengaluru,sanjay@gmail.com,104
17,EMP017,Kavya,27,Data Science,61000,2023-04-05,NaN,kavya@gmail.com,105
18,EMP018,Deepak,35,Finance,75000,2020-12-18,Mumbai,deepak@gmail.com,106
19,EMP019,Swati,24,HR,49000,2023-08-25,Hyderabad,swati@gmail.com,107
20,EMP020,Nikhil,29,IT,53000,2022-07-15,Chennai,nikhil@gmail.com,108

In [14]:
df['Age'] = pd.to_numeric(df['Age'])

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 20
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  20 non-null     object
 1   Name         20 non-null     object
 2   Age          20 non-null     int64
 3   Department   20 non-null     object
 4   Salary       19 non-null     object
 5   Join_Date    19 non-null     object
 6   City         19 non-null     object
 7   Email        19 non-null     object
 8   Temp_Column  20 non-null     int64
dtypes: int64(2), object(7)
memory usage: 1.6+ KB

In [16]:
df.isnull().sum()

Employee_ID    0
Name           0
Age            0
Department     0
Salary         1
Join_Date      1
City           1
Email          1
Temp_Column    0
dtype: int64

In [17]:
df['Salary']

0             45000
1             52000
2               NaN
3             65000
5             55000
6             60000
7             50000
8             72000
9             47000
10            47000
11            58000
12            62000
13    not available
14            51000
15            42000
16            57000
17            61000
18            75000
19            49000
20            53000
Name: Salary, dtype: object

In [18]:

#  error='coerce' 
#  not available convert into NaN value 
# string values converted to Nan 


df['Salary'] = pd.to_numeric(df['Salary'] , errors='coerce')
df['Salary']

0     45000.0
1     52000.0
2         NaN
3     65000.0
5     55000.0
6     60000.0
7     50000.0
8     72000.0
9     47000.0
10    47000.0
11    58000.0
12    62000.0
13        NaN
14    51000.0
15    42000.0
16    57000.0
17    61000.0
18    75000.0
19    49000.0
20    53000.0
Name: Salary, dtype: float64

In [19]:
df['Salary'].fillna(df['Salary'].mean() , inplace=True)

In [20]:
df['Salary'].isnull().sum()

np.int64(0)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 20
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  20 non-null     object
 1   Name         20 non-null     object
 2   Age          20 non-null     int64
 3   Department   20 non-null     object
 4   Salary       20 non-null     float64
 5   Join_Date    19 non-null     object
 6   City         19 non-null     object
 7   Email        19 non-null     object
 8   Temp_Column  20 non-null     int64
dtypes: float64(1), int64(2), object(6)
memory usage: 1.6+ KB

In [22]:
df.isnull().sum()

Employee_ID    0
Name           0
Age            0
Department     0
Salary         0
Join_Date      1
City           1
Email          1
Temp_Column    0
dtype: int64

In [24]:
df.dropna(subset='Join_Date' , inplace=True)

In [30]:
df.Join_Date

0     2023-01-15
1     2022-06-20
2     2023-03-10
3     2021-11-05
6     2022-09-18
7     2023-02-28
8     2020-08-14
9     2023-05-22
10    2023-05-22
11    2022-12-01
12    2021-10-10
13    2019-04-15
14    2023-06-30
15    2024-01-10
16    2022-02-29
17    2023-04-05
18    2020-12-18
19    2023-08-25
20    2022-07-15
Name: Join_Date, dtype: object

In [31]:
df['Join_Date'] = pd.to_datetime(df['Join_Date'] , errors='coerce')

In [32]:
df.isnull().sum()

Employee_ID    0
Name           0
Age            0
Department     0
Salary         0
Join_Date      1
City           1
Email          1
Temp_Column    0
dtype: int64

In [37]:
df['Join_Date'][16] = 'NaN'

D:\TEMP\ipykernel_11572\1794651760.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Join_Date'][16] = 'NaN'

In [38]:
df.dropna(subset='Join_Date', inplace=True)

In [39]:
df['Join_Date'].isnull().sum()

np.int64(0)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18 entries, 0 to 20
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  18 non-null     object
 1   Name         18 non-null     object
 2   Age          18 non-null     int64
 3   Department   18 non-null     object
 4   Salary       18 non-null     float64
 5   Join_Date    18 non-null     datetime64[ns]
 6   City         17 non-null     object
 7   Email        17 non-null     object
 8   Temp_Column  18 non-null     int64
dtypes: datetime64[ns](1), float64(1), int64(2), object(5)
memory usage: 1.4+ KB

In [42]:
df.isnull().sum()

Employee_ID    0
Name           0
Age            0
Department     0
Salary         0
Join_Date      0
City           1
Email          1
Temp_Column    0
dtype: int64

In [44]:
df['City'].fillna('Others' , inplace=True)

In [46]:
df.isnull().sum()

Employee_ID    0
Name           0
Age            0
Department     0
Salary         0
Join_Date      0
City           0
Email          1
Temp_Column    0
dtype: int64

In [48]:
df['Email'].fillna('Other_email' , inplace=True)

In [50]:
df.isnull().sum()

Employee_ID    0
Name           0
Age            0
Department     0
Salary         0
Join_Date      0
City           0
Email          0
Temp_Column    0
dtype: int64

In [51]:
df.duplicated().sum()

np.int64(1)

In [52]:
df.drop_duplicates(inplace=True)
df

,Employee_ID,Name,Age,Department,Salary,Join_Date,City,Email,Temp_Column
0,EMP001,Rahul,25,Data Analytics,45000.000000,2023-01-15,Bengaluru,rahul@gmail.com,123
1,EMP002,Priya,28,HR,52000.000000,2022-06-20,Hyderabad,priya@gmail.com,456
2,EMP003,Amit,24,Data Science,55611.111111,2023-03-10,Pune,amit@gmail.com,789
3,EMP004,Neha,30,Finance,65000.000000,2021-11-05,Mumbai,neha@gmail.com,111
6,EMP007,Arjun,29,Data Science,60000.000000,2022-09-18,Delhi,arjun@gmail.com,444
7,EMP008,Meera,26,HR,50000.000000,2023-02-28,Hyderabad,meera@gmail.com,555
8,EMP009,Kiran,31,Finance,72000.000000,2020-08-14,Mumbai,Other_email,666
9,EMP010,Anjali,25,IT,47000.000000,2023-05-22,Pune,anjali@gmail.com,777
11,EMP011,Varun,29,Data Analytics,58000.000000,2022-12-01,Bengaluru,varun@gmail.com,888
12,EMP012,Pooja,27,Data Science,62000.000000,2021-10-10,Chennai,pooja@gmail.com,999
13,EMP013,Rohit,32,Finance,55611.111111,2019-04-15,Mumbai,rohit@gmail.com,101
14,EMP014,Divya,26,HR,51000.000000,2023-06-30,Hyderabad,divya@gmail.com,102
15,EMP015,Manoj,23,IT,42000.000000,2024-01-10,Pune,manoj@gmail.com,103
17,EMP017,Kavya,27,Data Science,61000.000000,2023-04-05,Others,kavya@gmail.com,105
18,EMP018,Deepak,35,Finance,75000.000000,2020-12-18,Mumbai,deepak@gmail.com,106
19,EMP019,Swati,24,HR,49000.000000,2023-08-25,Hyderabad,swati@gmail.com,107
20,EMP020,Nikhil,29,IT,53000.000000,2022-07-15,Chennai,nikhil@gmail.com,108

In [53]:
df.duplicated().sum()

np.int64(0)

In [54]:
df.reset_index(drop=True , inplace=True)

In [55]:
df

,Employee_ID,Name,Age,Department,Salary,Join_Date,City,Email,Temp_Column
0,EMP001,Rahul,25,Data Analytics,45000.000000,2023-01-15,Bengaluru,rahul@gmail.com,123
1,EMP002,Priya,28,HR,52000.000000,2022-06-20,Hyderabad,priya@gmail.com,456
2,EMP003,Amit,24,Data Science,55611.111111,2023-03-10,Pune,amit@gmail.com,789
3,EMP004,Neha,30,Finance,65000.000000,2021-11-05,Mumbai,neha@gmail.com,111
4,EMP007,Arjun,29,Data Science,60000.000000,2022-09-18,Delhi,arjun@gmail.com,444
5,EMP008,Meera,26,HR,50000.000000,2023-02-28,Hyderabad,meera@gmail.com,555
6,EMP009,Kiran,31,Finance,72000.000000,2020-08-14,Mumbai,Other_email,666
7,EMP010,Anjali,25,IT,47000.000000,2023-05-22,Pune,anjali@gmail.com,777
8,EMP011,Varun,29,Data Analytics,58000.000000,2022-12-01,Bengaluru,varun@gmail.com,888
9,EMP012,Pooja,27,Data Science,62000.000000,2021-10-10,Chennai,pooja@gmail.com,999
10,EMP013,Rohit,32,Finance,55611.111111,2019-04-15,Mumbai,rohit@gmail.com,101
11,EMP014,Divya,26,HR,51000.000000,2023-06-30,Hyderabad,divya@gmail.com,102
12,EMP015,Manoj,23,IT,42000.000000,2024-01-10,Pune,manoj@gmail.com,103
13,EMP017,Kavya,27,Data Science,61000.000000,2023-04-05,Others,kavya@gmail.com,105
14,EMP018,Deepak,35,Finance,75000.000000,2020-12-18,Mumbai,deepak@gmail.com,106
15,EMP019,Swati,24,HR,49000.000000,2023-08-25,Hyderabad,swati@gmail.com,107
16,EMP020,Nikhil,29,IT,53000.000000,2022-07-15,Chennai,nikhil@gmail.com,108