In [51]:
import pandas as pd

In [52]:
df = pd.read_csv("data/sales_data.csv")

In [53]:
df.head()

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie

In [54]:
df.tail()

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning,0.29,Cash,Online,North-Charlie
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New,0.21,Bank Transfer,Retail,North-Bob
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David
998,1100,2023-12-20,David,West,1629.47,39,Electronics,3685.03,3743.39,New,0.01,Bank Transfer,Online,West-David
999,1086,2023-08-16,Alice,East,4923.93,48,Food,2632.58,2926.68,Returning,0.14,Cash,Online,East-Alice

In [55]:
df.shape

(1000, 14)

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Product_ID            1000 non-null   int64
 1   Sale_Date             1000 non-null   object
 2   Sales_Rep             1000 non-null   object
 3   Region                1000 non-null   object
 4   Sales_Amount          1000 non-null   float64
 5   Quantity_Sold         1000 non-null   int64
 6   Product_Category      1000 non-null   object
 7   Unit_Cost             1000 non-null   float64
 8   Unit_Price            1000 non-null   float64
 9   Customer_Type         1000 non-null   object
 10  Discount              1000 non-null   float64
 11  Payment_Method        1000 non-null   object
 12  Sales_Channel         1000 non-null   object
 13  Region_and_Sales_Rep  1000 non-null   object
dtypes: float64(4), int64(2), object(8)
memory usage: 109.5+ KB

In [57]:
df.describe()

,Product_ID,Sales_Amount,Quantity_Sold,Unit_Cost,Unit_Price,Discount
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000
mean,1050.128000,5019.265230,25.355000,2475.304550,2728.440120,0.15239
std,29.573505,2846.790126,14.159006,1417.872546,1419.399839,0.08720
min,1001.000000,100.120000,1.000000,60.280000,167.120000,0.00000
25%,1024.000000,2550.297500,13.000000,1238.380000,1509.085000,0.08000
50%,1051.000000,5019.300000,25.000000,2467.235000,2696.400000,0.15000
75%,1075.000000,7507.445000,38.000000,3702.865000,3957.970000,0.23000
max,1100.000000,9989.040000,49.000000,4995.300000,5442.150000,0.30000

In [58]:
df.columns

Index(['Product_ID', 'Sale_Date', 'Sales_Rep', 'Region', 'Sales_Amount',
       'Quantity_Sold', 'Product_Category', 'Unit_Cost', 'Unit_Price',
       'Customer_Type', 'Discount', 'Payment_Method', 'Sales_Channel',
       'Region_and_Sales_Rep'],
      dtype='object')

## Task

In [59]:
# Number of rows:
# Number of columns:

# Column names:

# Numerical columns:

# Text columns:

# Date columns:

# Missing values:

# Duplicate rows:

In [60]:
print("number of rows :- " , df.shape[0])

number of rows :-  1000

In [61]:
print("number of columns :- " , df.shape[1])

number of columns :-  14

In [62]:
print("column names :- \n" , df.columns)

column names :-
 Index(['Product_ID', 'Sale_Date', 'Sales_Rep', 'Region', 'Sales_Amount',
       'Quantity_Sold', 'Product_Category', 'Unit_Cost', 'Unit_Price',
       'Customer_Type', 'Discount', 'Payment_Method', 'Sales_Channel',
       'Region_and_Sales_Rep'],
      dtype='object')

In [63]:
print("numerical columns :- \n", df.select_dtypes(include="number"))

numerical columns :-
      Product_ID  Sales_Amount  Quantity_Sold  Unit_Cost  Unit_Price  Discount
0          1052       5053.97             18     152.75      267.22      0.09
1          1093       4384.02             17    3816.39     4209.44      0.11
2          1015       4631.23             30     261.56      371.40      0.20
3          1072       2167.94             39    4330.03     4467.75      0.02
4          1061       3750.20             13     637.37      692.71      0.08
..          ...           ...            ...        ...         ...       ...
995        1010       4733.88              4    4943.03     5442.15      0.29
996        1067       4716.36             37    1754.32     1856.40      0.21
997        1018       7629.70             17     355.72      438.27      0.06
998        1100       1629.47             39    3685.03     3743.39      0.01
999        1086       4923.93             48    2632.58     2926.68      0.14

[1000 rows x 6 columns]

In [71]:
print("categorical columns :- \n", df.select_dtypes(include="object"))

categorical columns :-
     Sales_Rep Region Product_Category Customer_Type Payment_Method  \
0         Bob  North        Furniture     Returning           Cash
1         Bob   West        Furniture     Returning           Cash
2       David  South             Food     Returning  Bank Transfer
3         Bob  South         Clothing           New    Credit Card
4     Charlie   East      Electronics           New    Credit Card
..        ...    ...              ...           ...            ...
995   Charlie  North             Food     Returning           Cash
996       Bob  North         Clothing           New  Bank Transfer
997     David  South         Clothing     Returning  Bank Transfer
998     David   West      Electronics           New  Bank Transfer
999     Alice   East             Food     Returning           Cash

    Sales_Channel Region_and_Sales_Rep
0          Online            North-Bob
1          Retail             West-Bob
2          Retail          South-David
3          Retail            South-Bob
4          Online         East-Charlie
..            ...                  ...
995        Online        North-Charlie
996        Retail            North-Bob
997        Online          South-David
998        Online           West-David
999        Online           East-Alice

[1000 rows x 7 columns]

In [65]:
df['Sale_Date'] = pd.to_datetime(df['Sale_Date'])

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Product_ID            1000 non-null   int64
 1   Sale_Date             1000 non-null   datetime64[ns]
 2   Sales_Rep             1000 non-null   object
 3   Region                1000 non-null   object
 4   Sales_Amount          1000 non-null   float64
 5   Quantity_Sold         1000 non-null   int64
 6   Product_Category      1000 non-null   object
 7   Unit_Cost             1000 non-null   float64
 8   Unit_Price            1000 non-null   float64
 9   Customer_Type         1000 non-null   object
 10  Discount              1000 non-null   float64
 11  Payment_Method        1000 non-null   object
 12  Sales_Channel         1000 non-null   object
 13  Region_and_Sales_Rep  1000 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(2), object(7)
memory usage: 109.5+ KB

In [67]:
df.select_dtypes(include="datetime")

     Sale_Date
0   2023-02-03
1   2023-04-21
2   2023-09-21
3   2023-08-24
4   2023-03-24
..         ...
995 2023-04-15
996 2023-09-07
997 2023-04-27
998 2023-12-20
999 2023-08-16

[1000 rows x 1 columns]

In [72]:
df.isnull().sum()

Product_ID              0
Sale_Date               0
Sales_Rep               0
Region                  0
Sales_Amount            0
Quantity_Sold           0
Product_Category        0
Unit_Cost               0
Unit_Price              0
Customer_Type           0
Discount                0
Payment_Method          0
Sales_Channel           0
Region_and_Sales_Rep    0
dtype: int64

In [75]:
df.duplicated().sum()

np.int64(0)