## Pandas

- Pandas are the Python library used to work with tabluer datasets
- Pandas are mainly work with series and dataframes datasets 
- Pandas are used data manupulation , cleaning , EDA , organise the messy data into clean format

In [1]:
import pandas as pd

In [10]:
# Series  1-D

ages = pd.Series([25, 28, 30, 26])
ages

0    25
1    28
2    30
3    26
dtype: int64

In [12]:
# dataframes - 2D

data = {
    "name": ["Rahul", "Priya", "Amit"],
    "age": [25, 28, 30],
    "salary": [50000, 60000, 45000]
}

df = pd.DataFrame(data)

print(df)

    name  age  salary
0  Rahul   25   50000
1  Priya   28   60000
2   Amit   30   45000

In [13]:
df.head() # top 5 lines

    name  age  salary
0  Rahul   25   50000
1  Priya   28   60000
2   Amit   30   45000

In [14]:
df.tail() # bottom 5 lines

    name  age  salary
0  Rahul   25   50000
1  Priya   28   60000
2   Amit   30   45000

In [15]:
df.info()  #  information about the coumns like how many columns what data type of columns how many non-null vlaues

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   salary  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [18]:
df.describe()  # it gives statistical summery like count ,mean , std , min , 25% , 50% , 75% , max
# it is applicable for numericals columns only

             age        salary
count   3.000000      3.000000
mean   27.666667  51666.666667
std     2.516611   7637.626158
min    25.000000  45000.000000
25%    26.500000  47500.000000
50%    28.000000  50000.000000
75%    29.000000  55000.000000
max    30.000000  60000.000000

In [20]:
# selecting columns 
# for one column

df['name']

0    Rahul
1    Priya
2     Amit
Name: name, dtype: object

In [21]:
# more then 1 columns

df[['name','salary']]

    name  salary
0  Rahul   50000
1  Priya   60000
2   Amit   45000

## Practice

In [23]:
# # Create a DataFrame with at least 10 customers containing:

# # customer
# # age
# # city
# # salary

# Find:

# Average salary
# Highest salary
# Lowest salary
# Number of customers
# Customer and salary columns

In [25]:
data1 = {
    'customer' : ['naresh','suresh','mahesh','tom','sam','ram','roy','rohith','virat','varun'] ,
    'age' : [23,43,54,34,33,24,56,43,45,67] ,
    'City' : ['pune','bengaluru','delhi','goa','mumbai','pune','pune','jaipure','amrithsar','bengaluru']  ,
    'salary' : [30000,25000,60000,55000,65000,54000,34000,70000,86000,100000]
}

df = pd.DataFrame(data1)
df

  customer  age       City  salary
0   naresh   23       pune   30000
1   suresh   43  bengaluru   25000
2   mahesh   54      delhi   60000
3      tom   34        goa   55000
4      sam   33     mumbai   65000
5      ram   24       pune   54000
6      roy   56       pune   34000
7   rohith   43    jaipure   70000
8    virat   45  amrithsar   86000
9    varun   67  bengaluru  100000

In [35]:
# average salary
print("total salary :- ",sum(df['salary']))
print("length" , len(df['salary']))
print("avg sal :-", sum(df['salary'])/len(df['salary']))

total salary :-  579000
length 10
avg sal :- 57900.0

In [37]:
max(df['salary'])  # max salary

100000

In [38]:
min(df['salary'])  # min salary

25000

In [41]:
len(df['customer']) # number of customers

10

In [42]:
df[['customer','salary']]

  customer  salary
0   naresh   30000
1   suresh   25000
2   mahesh   60000
3      tom   55000
4      sam   65000
5      ram   54000
6      roy   34000
7   rohith   70000
8    virat   86000
9    varun  100000