In [11]:
import pandas as pd

In [12]:
customer_data = {
    "customer_id": [1, 2, 3],
    "name": ["Rahul", "Priya", "Amit"],
    "city": ["Bangalore", "Pune", "Mumbai"]
}

customer = pd.DataFrame(customer_data)
customer

   customer_id   name       city
0            1  Rahul  Bangalore
1            2  Priya       Pune
2            3   Amit     Mumbai

In [13]:
order_data = {
    "order_id": [101, 102, 103],
    "customer_id": [1, 2, 1],
    "product": ["Laptop", "Mouse", "Monitor"],
    "amount": [60000, 1000, 15000]
}
order = pd.DataFrame(order_data)
order

   order_id  customer_id  product  amount
0       101            1   Laptop   60000
1       102            2    Mouse    1000
2       103            1  Monitor   15000

In [ ]:
# using merge how we can perform inner join

merged = pd.merge(
    customer,  
    order,
    on='customer_id',
    how='inner'
)
merged

   customer_id   name       city  order_id  product  amount
0            1  Rahul  Bangalore       101   Laptop   60000
1            1  Rahul  Bangalore       103  Monitor   15000
2            2  Priya       Pune       102    Mouse    1000

In [17]:
df = pd.read_csv("../day-03/data/sales_data.csv")

In [22]:
df.head(1)

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob

## Task

In [16]:
# Total sales
# Average sales
# Sales by product
# Sales by category
# Sales by city
# Top-selling product
# Average sales per category
# Transactions per category

In [18]:
df['Sales_Amount'].sum() # Total sales

np.float64(5019265.2299999995)

In [19]:
df['Sales_Amount'].mean() # Average sales

np.float64(5019.265229999999)

In [21]:
# Sales by product

df.groupby('Product_Category')['Sales_Amount'].sum()

Product_Category
Clothing       1313474.36
Electronics    1243499.64
Food           1201773.54
Furniture      1260517.69
Name: Sales_Amount, dtype: float64

In [ ]:
# Sales by Customer_Type category

df.groupby('Customer_Type')['Sales_Amount'].sum()

Customer_Type
New          2506258.30
Returning    2513006.93
Name: Sales_Amount, dtype: float64

In [24]:
# Sales by city

df.groupby('Region')['Sales_Amount'].sum()

Region
East     1259792.93
North    1369612.51
South    1154250.86
West     1235608.93
Name: Sales_Amount, dtype: float64

In [25]:
# Top-selling product

df.groupby('Product_Category')['Sales_Amount'].max()

Product_Category
Clothing       9972.66
Electronics    9914.15
Food           9989.04
Furniture      9976.52
Name: Sales_Amount, dtype: float64

In [28]:
# Average sales per category

df.groupby('Product_Category')['Sales_Amount'].mean()

Product_Category
Clothing       4901.023731
Electronics    5054.876585
Food           5317.582035
Furniture      4848.144962
Name: Sales_Amount, dtype: float64

In [29]:
# Transactions per category

df['Product_Category'].value_counts()

Product_Category
Clothing       268
Furniture      260
Electronics    246
Food           226
Name: count, dtype: int64

In [30]:
df.groupby('Product_Category').size()

Product_Category
Clothing       268
Electronics    246
Food           226
Furniture      260
dtype: int64

In [32]:
df.groupby('Product_Category')['Product_Category'].count()

Product_Category
Clothing       268
Electronics    246
Food           226
Furniture      260
Name: Product_Category, dtype: int64

In [ ]:
# and find:

# Customer spending
# Revenue by city
# Orders per customer

In [33]:
customer

   customer_id   name       city
0            1  Rahul  Bangalore
1            2  Priya       Pune
2            3   Amit     Mumbai

In [34]:
order

   order_id  customer_id  product  amount
0       101            1   Laptop   60000
1       102            2    Mouse    1000
2       103            1  Monitor   15000

In [39]:
new_df = pd.merge(
    customer,
    order,
    on='customer_id',
    how='inner'
)
new_df

   customer_id   name       city  order_id  product  amount
0            1  Rahul  Bangalore       101   Laptop   60000
1            1  Rahul  Bangalore       103  Monitor   15000
2            2  Priya       Pune       102    Mouse    1000

In [48]:

# Customers total spending

new_df['amount'].sum()

np.int64(76000)

In [49]:
new_df.groupby('customer_id')['amount'].sum()   # each customer spending

customer_id
1    75000
2     1000
Name: amount, dtype: int64

In [45]:
# Revenue by city

new_df.groupby('city')['amount'].sum()

city
Bangalore    75000
Pune          1000
Name: amount, dtype: int64

In [46]:
# Orders per customer

new_df.groupby('customer_id')['customer_id'].count()

customer_id
1    2
2    1
Name: customer_id, dtype: int64

In [50]:
new_df['customer_id'].value_counts()

customer_id
1    2
2    1
Name: count, dtype: int64