## imported libraries

In [1]:
import pandas as pd

## Load Dataset

In [13]:
df = pd.read_csv("./data/sales_data.csv")

## Understanding Datasets

In [15]:
df.head()

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie

In [16]:
df.tail()

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning,0.29,Cash,Online,North-Charlie
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New,0.21,Bank Transfer,Retail,North-Bob
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David
998,1100,2023-12-20,David,West,1629.47,39,Electronics,3685.03,3743.39,New,0.01,Bank Transfer,Online,West-David
999,1086,2023-08-16,Alice,East,4923.93,48,Food,2632.58,2926.68,Returning,0.14,Cash,Online,East-Alice

In [17]:
df.shape

(1000, 14)

In [18]:
df.columns

Index(['Product_ID', 'Sale_Date', 'Sales_Rep', 'Region', 'Sales_Amount',
       'Quantity_Sold', 'Product_Category', 'Unit_Cost', 'Unit_Price',
       'Customer_Type', 'Discount', 'Payment_Method', 'Sales_Channel',
       'Region_and_Sales_Rep'],
      dtype='object')

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Product_ID            1000 non-null   int64
 1   Sale_Date             1000 non-null   object
 2   Sales_Rep             1000 non-null   object
 3   Region                1000 non-null   object
 4   Sales_Amount          1000 non-null   float64
 5   Quantity_Sold         1000 non-null   int64
 6   Product_Category      1000 non-null   object
 7   Unit_Cost             1000 non-null   float64
 8   Unit_Price            1000 non-null   float64
 9   Customer_Type         1000 non-null   object
 10  Discount              1000 non-null   float64
 11  Payment_Method        1000 non-null   object
 12  Sales_Channel         1000 non-null   object
 13  Region_and_Sales_Rep  1000 non-null   object
dtypes: float64(4), int64(2), object(8)
memory usage: 109.5+ KB

In [20]:
df.describe()

,Product_ID,Sales_Amount,Quantity_Sold,Unit_Cost,Unit_Price,Discount
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000
mean,1050.128000,5019.265230,25.355000,2475.304550,2728.440120,0.15239
std,29.573505,2846.790126,14.159006,1417.872546,1419.399839,0.08720
min,1001.000000,100.120000,1.000000,60.280000,167.120000,0.00000
25%,1024.000000,2550.297500,13.000000,1238.380000,1509.085000,0.08000
50%,1051.000000,5019.300000,25.000000,2467.235000,2696.400000,0.15000
75%,1075.000000,7507.445000,38.000000,3702.865000,3957.970000,0.23000
max,1100.000000,9989.040000,49.000000,4995.300000,5442.150000,0.30000

## checking Data Quality

In [21]:
df.isnull().sum()

Product_ID              0
Sale_Date               0
Sales_Rep               0
Region                  0
Sales_Amount            0
Quantity_Sold           0
Product_Category        0
Unit_Cost               0
Unit_Price              0
Customer_Type           0
Discount                0
Payment_Method          0
Sales_Channel           0
Region_and_Sales_Rep    0
dtype: int64

In [22]:
df.duplicated().sum()

np.int64(0)

In [25]:
df.dtypes

Product_ID                int64
Sale_Date                object
Sales_Rep                object
Region                   object
Sales_Amount            float64
Quantity_Sold             int64
Product_Category         object
Unit_Cost               float64
Unit_Price              float64
Customer_Type            object
Discount                float64
Payment_Method           object
Sales_Channel            object
Region_and_Sales_Rep     object
dtype: object

## data Cleaning fixing the missing values , nan , data types of columns

In [27]:
df.Sale_Date.isnull().sum()

np.int64(0)

In [28]:
df['Sale_Date'] = pd.to_datetime(df['Sale_Date'] , errors='coerce')
df.dtypes

Product_ID                       int64
Sale_Date               datetime64[ns]
Sales_Rep                       object
Region                          object
Sales_Amount                   float64
Quantity_Sold                    int64
Product_Category                object
Unit_Cost                      float64
Unit_Price                     float64
Customer_Type                   object
Discount                       float64
Payment_Method                  object
Sales_Channel                   object
Region_and_Sales_Rep            object
dtype: object

In [30]:
df['Sales_Rep'].head()

0        Bob
1        Bob
2      David
3        Bob
4    Charlie
Name: Sales_Rep, dtype: object

In [31]:
df['Sales_Rep'].isnull().sum()

np.int64(0)

In [33]:
df.duplicated().sum()

np.int64(0)

## Create a calculated column

In [34]:
df.head()

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie

In [35]:
df['revenue'] = df['Unit_Price'] * df['Quantity_Sold']
df['revenue']

0        4809.96
1       71560.48
2       11142.00
3      174242.25
4        9005.23
         ...
995     21768.60
996     68686.80
997      7450.59
998    145992.21
999    140480.64
Name: revenue, Length: 1000, dtype: float64

Total revenue

Average order value

Highest order

Lowest order

In [38]:
df['Sales_Amount'].sum()

np.float64(5019265.2299999995)

In [37]:
df['Unit_Price'].mean()

np.float64(2728.44012)

In [40]:
df['Quantity_Sold'].max()

49

In [41]:
df['Quantity_Sold'].min()

1

In [42]:
# Calculate:

# Revenue by product
# Revenue by category
# Revenue by city
# Revenue by customer

In [46]:
df.groupby('Product_Category')['Sales_Amount'].sum()

Product_Category
Clothing       1313474.36
Electronics    1243499.64
Food           1201773.54
Furniture      1260517.69
Name: Sales_Amount, dtype: float64

In [47]:
df.groupby('Payment_Method')['Sales_Amount'].sum()

Payment_Method
Bank Transfer    1717363.17
Cash             1544338.54
Credit Card      1757563.52
Name: Sales_Amount, dtype: float64

In [48]:
df.groupby('Region_and_Sales_Rep')['Sales_Amount'].sum()

Region_and_Sales_Rep
East-Alice       260789.47
East-Bob         309876.11
East-Charlie     165172.94
East-David       284613.51
East-Eve         239340.90
North-Alice      249647.22
North-Bob        233464.81
North-Charlie    299789.01
North-David      282539.27
North-Eve        304172.20
South-Alice      239414.54
South-Bob        251200.43
South-Charlie    156140.68
South-David      311416.99
South-Eve        196078.22
West-Alice       215690.54
West-Bob         286449.28
West-Charlie     239708.85
West-David       263167.59
West-Eve         230592.67
Name: Sales_Amount, dtype: float64

In [49]:

df.groupby('Customer_Type')['Sales_Amount'].sum()

Customer_Type
New          2506258.30
Returning    2513006.93
Name: Sales_Amount, dtype: float64

In [68]:
# Which product generates the most revenue?

df.head(1)

df.groupby('Product_Category')['Sales_Amount'].max().sort_values(ascending=False)

Product_Category
Food           9989.04
Furniture      9976.52
Clothing       9972.66
Electronics    9914.15
Name: Sales_Amount, dtype: float64

In [66]:
# Which category generates the most revenue?

df.head(1)

df.groupby('Sales_Channel')['Sales_Amount'].max().sort_values(ascending=False)

Sales_Channel
Retail    9989.04
Online    9972.66
Name: Sales_Amount, dtype: float64

In [70]:
# Which month has the highest sales?

df.head(1)

df['Sale_Date'].head()

0   2023-02-03
1   2023-04-21
2   2023-09-21
3   2023-08-24
4   2023-03-24
Name: Sale_Date, dtype: datetime64[ns]

In [74]:
df['Months'] = df['Sale_Date'].dt.month
df['Months'].head()

0    2
1    4
2    9
3    8
4    3
Name: Months, dtype: int32

In [75]:
df['Years'] = df['Sale_Date'].dt.year
df['Years'].head()

0    2023
1    2023
2    2023
3    2023
4    2023
Name: Years, dtype: int32

In [76]:
df['day'] = df['Sale_Date'].dt.day
df['day'].head()

0     3
1    21
2    21
3    24
4    24
Name: day, dtype: int32

In [78]:
df.groupby('Months')['Sales_Amount'].max().sort_values(ascending=False)

Months
12    9989.04
8     9976.52
4     9961.96
10    9933.22
9     9914.15
1     9813.81
2     9813.32
11    9762.54
3     9755.90
5     9744.52
6     9736.49
7     9638.64
Name: Sales_Amount, dtype: float64

In [81]:
# What is the average order value?

df.head(1)

df['Unit_Price'].mean()

np.float64(2728.44012)

In [88]:
# Which customer purchases most frequently?

df.groupby('Customer_Type')['Quantity_Sold'].count()

Customer_Type
New          504
Returning    496
Name: Quantity_Sold, dtype: int64

In [90]:
# Which city generates the highest revenue?
df.groupby('Region')['Sales_Amount'].max().sort_values(ascending=False)

Region
North    9989.04
South    9961.96
East     9948.71
West     9933.22
Name: Sales_Amount, dtype: float64

In [93]:
# Which product has the lowest revenue?

df.groupby('Product_Category')['Sales_Amount'].min().sort_values(ascending=True)

Product_Category
Clothing       100.12
Furniture      113.40
Food           114.59
Electronics    189.48
Name: Sales_Amount, dtype: float64

In [94]:
df.head()

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep,revenue,Months,Years,day
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob,4809.96,2,2023,3
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob,71560.48,4,2023,21
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David,11142.00,9,2023,21
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob,174242.25,8,2023,24
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie,9005.23,3,2023,24

In [97]:
#  How many transactions are there?

df.shape[0]

1000

In [106]:
# What percentage of transactions are above average order value?

above_avg = df[ df['Sales_Amount'] > (df['Sales_Amount'].mean())]
leng = len(above_avg)
percentage = leng/len(df)*100
percentage

50.0

In [109]:
# Which category has the highest average order value?

df.groupby('Product_Category')['Sales_Amount'].mean().sort_values(ascending=False)

Product_Category
Food           5317.582035
Electronics    5054.876585
Clothing       4901.023731
Furniture      4848.144962
Name: Sales_Amount, dtype: float64